### ISSUE TITLE
Drofa under Fritz

### ISSUE THREAD

**Issue by SzotsGabor** [justNo4b/Drofa#205]
Not a big issue but still. Drofa is OK under Fritz but its installation is not seamless. When I open the options window (e.g. for changing the default number of threads which Fritz 17 sets to 4 initially) then try to save the engine, I can't, nothing happens. I have to create a .uci file for Fritz and edit the options manually. After that Fritz can use Drofa without further issues.
BTW, I have similar a issue with SlowChess Blitz.

Apologies if this was not clear.

BTW, when will this release be finalized (that is, not a pre-release)?

**Comment by justNo4b** [comment]
I will see if I able to get Fritz GUI, because figuring out this issue without it would be a hassle.

Currently, there is no set time for a 4.0.0 release.
I mapped a set of features I want to see before release, the main would be:

KP_network for evaluation
FRC handling
Some small bugfixes in the multythreading code
>15 elo gain needed to release (likely will be covered by KP net)

While work is already in progress, I dont have much time now, so I cannot give any precise date.

**Comment by SzotsGabor** [comment]
> I will see if I able to get Fritz GUI, because figuring out this issue without it would be a hassle.
> 

I suspect it has to do with the id authors... line. Under Shredder, no authors are displayed when installing and installation is unsuccessful. However, if, during installation, I fill the authors field with 'Alexander Litov', it's OK. So maybe the authors id is too long or it has problem with the '&' or maybe the problem is 'authors' instead of 'author'.

**Comment by SzotsGabor** [comment]
I think I have identified the problem with Fritz. It seems the GUI does not understand the id 'authors'. When I remove the final 's' (in uci.cc), it can install the engine without problems.

**Comment by justNo4b** [comment]
Should be fixed with [3e0351e](https://github.com/justNo4b/Drofa/commit/3e0351efad8564d6dd71be0fe99606503d27585e)
